name: Deploy to VPS

on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "/*"
        target: "/var/www/Wahbt/newHrFactoryapp"  # Adjust your VPS directory

    - name: SSH Command to Pull Latest Code
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/Wahbt/newHrFactoryapp
          git pull origin main  # Adjust branch if needed
          composer install  # Run other commands like migrations, etc.
          #php artisan migrate
